# coding: utf-8

"""
    Conekta API

    Conekta sdk  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Contact: engineering@conekta.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import conekta
from conekta.api.transactions_api import TransactionsApi  # noqa: E501
from conekta.rest import ApiException


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self):
        self.api = conekta.api.transactions_api.TransactionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_transaction(self):
        """Test case for get_transaction

        Get transaction  # noqa: E501
        """
        pass

    def test_get_transactions(self):
        """Test case for get_transactions

        Get List transactions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
