# coding: utf-8

"""
    Conekta API

    Conekta sdk  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Contact: engineering@conekta.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import conekta
from conekta.api.webhooks_api import WebhooksApi  # noqa: E501
from conekta.rest import ApiException


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self):
        self.api = conekta.api.webhooks_api.WebhooksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_webhook(self):
        """Test case for create_webhook

        Create Webhook  # noqa: E501
        """
        pass

    def test_delete_webhook(self):
        """Test case for delete_webhook

        Delete Webhook  # noqa: E501
        """
        pass

    def test_get_webhook(self):
        """Test case for get_webhook

        Get Webhook  # noqa: E501
        """
        pass

    def test_get_webhooks(self):
        """Test case for get_webhooks

        Get List of Webhooks  # noqa: E501
        """
        pass

    def test_test_webhook(self):
        """Test case for test_webhook

        Test Webhook  # noqa: E501
        """
        pass

    def test_update_webhook(self):
        """Test case for update_webhook

        Update Webhook  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
