# coding: utf-8

"""
    Conekta API

    Conekta sdk  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Contact: engineering@conekta.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import conekta
from conekta.api.plans_api import PlansApi  # noqa: E501
from conekta.rest import ApiException


class TestPlansApi(unittest.TestCase):
    """PlansApi unit test stubs"""

    def setUp(self):
        self.api = conekta.api.plans_api.PlansApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_plan(self):
        """Test case for create_plan

        Create Plan  # noqa: E501
        """
        pass

    def test_delete_plan(self):
        """Test case for delete_plan

        Delete Plan  # noqa: E501
        """
        pass

    def test_get_plan(self):
        """Test case for get_plan

        Get Plan  # noqa: E501
        """
        pass

    def test_get_plans(self):
        """Test case for get_plans

        Get A List of Plans  # noqa: E501
        """
        pass

    def test_update_plan(self):
        """Test case for update_plan

        Update Plan  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
