# coding: utf-8

"""
    Conekta API

    Conekta sdk  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Contact: engineering@conekta.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import conekta
from conekta.api.discounts_api import DiscountsApi  # noqa: E501
from conekta.rest import ApiException


class TestDiscountsApi(unittest.TestCase):
    """DiscountsApi unit test stubs"""

    def setUp(self):
        self.api = conekta.api.discounts_api.DiscountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_orders_create_discount_line(self):
        """Test case for orders_create_discount_line

        Create Discount  # noqa: E501
        """
        pass

    def test_orders_delete_discount_lines(self):
        """Test case for orders_delete_discount_lines

        Delete Discount  # noqa: E501
        """
        pass

    def test_orders_update_discount_lines(self):
        """Test case for orders_update_discount_lines

        Update Discount  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
