# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.3.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from conekta.api.subscriptions_customer_portal_api import SubscriptionsCustomerPortalApi


class TestSubscriptionsCustomerPortalApi(unittest.TestCase):
    """SubscriptionsCustomerPortalApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionsCustomerPortalApi()

    def tearDown(self) -> None:
        pass

    def test_create_customer_portal(self) -> None:
        """Test case for create_customer_portal

        Create customer portal
        """
        pass

    def test_get_customer_portal(self) -> None:
        """Test case for get_customer_portal

        Get customer portal
        """
        pass


if __name__ == '__main__':
    unittest.main()
