# coding: utf-8

"""
    Conekta API

    Conekta sdk  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Contact: engineering@conekta.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import conekta
from conekta.api.payment_methods_api import PaymentMethodsApi  # noqa: E501
from conekta.rest import ApiException


class TestPaymentMethodsApi(unittest.TestCase):
    """PaymentMethodsApi unit test stubs"""

    def setUp(self):
        self.api = conekta.api.payment_methods_api.PaymentMethodsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_customer_payment_methods(self):
        """Test case for create_customer_payment_methods

        Create Payment Method  # noqa: E501
        """
        pass

    def test_delete_customer_payment_methods(self):
        """Test case for delete_customer_payment_methods

        Delete Payment Method  # noqa: E501
        """
        pass

    def test_get_customer_payment_methods(self):
        """Test case for get_customer_payment_methods

        Get Payment Methods  # noqa: E501
        """
        pass

    def test_update_customer_payment_methods(self):
        """Test case for update_customer_payment_methods

        Update Payment Method  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
