# coding: utf-8

"""
    Conekta API

    Conekta sdk  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Contact: engineering@conekta.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import conekta
from conekta.api.payment_link_api import PaymentLinkApi  # noqa: E501
from conekta.rest import ApiException


class TestPaymentLinkApi(unittest.TestCase):
    """PaymentLinkApi unit test stubs"""

    def setUp(self):
        self.api = conekta.api.payment_link_api.PaymentLinkApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_checkout(self):
        """Test case for cancel_checkout

        Cancel Payment Link  # noqa: E501
        """
        pass

    def test_create_checkout(self):
        """Test case for create_checkout

        Create Unique Payment Link  # noqa: E501
        """
        pass

    def test_email_checkout(self):
        """Test case for email_checkout

        Send an email  # noqa: E501
        """
        pass

    def test_get_checkout(self):
        """Test case for get_checkout

        Get a payment link by ID  # noqa: E501
        """
        pass

    def test_get_checkouts(self):
        """Test case for get_checkouts

        Get a list of payment links  # noqa: E501
        """
        pass

    def test_sms_checkout(self):
        """Test case for sms_checkout

        Send an sms  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
