# coding: utf-8

"""
    Conekta API

    Conekta sdk  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Contact: engineering@conekta.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import conekta
from conekta.api.orders_api import OrdersApi  # noqa: E501
from conekta.rest import ApiException


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self):
        self.api = conekta.api.orders_api.OrdersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_order(self):
        """Test case for cancel_order

        Cancel Order  # noqa: E501
        """
        pass

    def test_create_order(self):
        """Test case for create_order

        Create order  # noqa: E501
        """
        pass

    def test_get_order_by_id(self):
        """Test case for get_order_by_id

        Get Order  # noqa: E501
        """
        pass

    def test_get_orders(self):
        """Test case for get_orders

        Get a list of Orders  # noqa: E501
        """
        pass

    def test_order_cancel_refund(self):
        """Test case for order_cancel_refund

        Cancel Refund  # noqa: E501
        """
        pass

    def test_order_refund(self):
        """Test case for order_refund

        Refund Order  # noqa: E501
        """
        pass

    def test_orders_create_capture(self):
        """Test case for orders_create_capture

        Capture Order  # noqa: E501
        """
        pass

    def test_update_order(self):
        """Test case for update_order

        Update Order  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
