# coding: utf-8

"""
    Conekta API

    Conekta sdk  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Contact: engineering@conekta.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import conekta
from conekta.api.shippings_api import ShippingsApi  # noqa: E501
from conekta.rest import ApiException


class TestShippingsApi(unittest.TestCase):
    """ShippingsApi unit test stubs"""

    def setUp(self):
        self.api = conekta.api.shippings_api.ShippingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_orders_create_shipping(self):
        """Test case for orders_create_shipping

        Create Shipping  # noqa: E501
        """
        pass

    def test_orders_delete_shipping(self):
        """Test case for orders_delete_shipping

        Delete Shipping  # noqa: E501
        """
        pass

    def test_orders_update_shipping(self):
        """Test case for orders_update_shipping

        Update Shipping  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
