# coding: utf-8

"""
    Conekta API

    Conekta sdk  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Contact: engineering@conekta.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import conekta
from conekta.api.products_api import ProductsApi  # noqa: E501
from conekta.rest import ApiException


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self):
        self.api = conekta.api.products_api.ProductsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_orders_create_product(self):
        """Test case for orders_create_product

        Create Product  # noqa: E501
        """
        pass

    def test_orders_delete_product(self):
        """Test case for orders_delete_product

        Delete Product  # noqa: E501
        """
        pass

    def test_orders_update_product(self):
        """Test case for orders_update_product

        Update Product  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
