# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.3.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ChargeResponseRefundsData(BaseModel):
    """
    ChargeResponseRefundsData
    """ # noqa: E501
    amount: StrictInt = Field(json_schema_extra={"examples": [-15000]})
    auth_code: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["867372"]})
    created_at: StrictInt = Field(json_schema_extra={"examples": [1678226878]})
    expires_at: Optional[StrictInt] = Field(default=None, description="refund expiration date", json_schema_extra={"examples": [1678226878]})
    id: StrictStr = Field(json_schema_extra={"examples": ["6407b5bee1329a000175ba11"]})
    object: StrictStr = Field(json_schema_extra={"examples": ["refund"]})
    status: Optional[StrictStr] = Field(default=None, description="refund status", json_schema_extra={"examples": ["pending"]})
    __properties: ClassVar[List[str]] = ["amount", "auth_code", "created_at", "expires_at", "id", "object", "status"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChargeResponseRefundsData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChargeResponseRefundsData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount": obj.get("amount"),
            "auth_code": obj.get("auth_code"),
            "created_at": obj.get("created_at"),
            "expires_at": obj.get("expires_at"),
            "id": obj.get("id"),
            "object": obj.get("object"),
            "status": obj.get("status")
        })
        return _obj


