# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.3.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from conekta.models.chargeback_file_response import ChargebackFileResponse
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ChargebackResponse(BaseModel):
    """
    Chargeback object
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["chbk_2zPxWFUnGNLySoumn"]})
    status: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["lost"]})
    reason: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["unrecognized"]})
    note: Optional[StrictStr] = None
    followup_status: Optional[StrictStr] = None
    response_from_client: Optional[StrictStr] = None
    files: Optional[List[ChargebackFileResponse]] = None
    object: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["chargeback"]})
    charge_id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["6966a06c044243000156c24d"]})
    created_at: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1768846800]})
    evidence_due_by: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1769126399]})
    __properties: ClassVar[List[str]] = ["id", "status", "reason", "note", "followup_status", "response_from_client", "files", "object", "charge_id", "created_at", "evidence_due_by"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['won', 'lost', 'action_required', 'pending_review', 'under_review', 'covered', 'rt', 'rt_sent', 'represented']):
            raise ValueError("must be one of enum values ('won', 'lost', 'action_required', 'pending_review', 'under_review', 'covered', 'rt', 'rt_sent', 'represented')")
        return value

    @field_validator('reason')
    def reason_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['unrecognized', 'unauthorized', 'unauthorized_by_client', 'unrecognized_like_fraud', 'insufficient_evidence', 'illegible_evidence', 'general', 'late_evidence', 'incorrect_exchange', 'fraudulent_business', 'billing', 'twice_transaction', 'transaction_not_refunded', 'bank_doc_request', 'unrecognized_purchase', 'subscription_canceled', 'copy_of_purchase', 'differents_amounts', 'subscription_not_requested', 'damaged_products', 'show_documents', 'duplicate', 'fraudulent', 'service_canceled', 'product_unacceptable', 'product_not_received', 'incorrect_amount', 'chip_liabiliaty_shift', 'credit_not_processed']):
            raise ValueError("must be one of enum values ('unrecognized', 'unauthorized', 'unauthorized_by_client', 'unrecognized_like_fraud', 'insufficient_evidence', 'illegible_evidence', 'general', 'late_evidence', 'incorrect_exchange', 'fraudulent_business', 'billing', 'twice_transaction', 'transaction_not_refunded', 'bank_doc_request', 'unrecognized_purchase', 'subscription_canceled', 'copy_of_purchase', 'differents_amounts', 'subscription_not_requested', 'damaged_products', 'show_documents', 'duplicate', 'fraudulent', 'service_canceled', 'product_unacceptable', 'product_not_received', 'incorrect_amount', 'chip_liabiliaty_shift', 'credit_not_processed')")
        return value

    @field_validator('followup_status')
    def followup_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['customer_uncontacted', 'customer_contacted', 'customer_unreachable']):
            raise ValueError("must be one of enum values ('customer_uncontacted', 'customer_contacted', 'customer_unreachable')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChargebackResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in files (list)
        _items = []
        if self.files:
            for _item_files in self.files:
                if _item_files:
                    _items.append(_item_files.to_dict())
            _dict['files'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChargebackResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "status": obj.get("status"),
            "reason": obj.get("reason"),
            "note": obj.get("note"),
            "followup_status": obj.get("followup_status"),
            "response_from_client": obj.get("response_from_client"),
            "files": [ChargebackFileResponse.from_dict(_item) for _item in obj["files"]] if obj.get("files") is not None else None,
            "object": obj.get("object"),
            "charge_id": obj.get("charge_id"),
            "created_at": obj.get("created_at"),
            "evidence_due_by": obj.get("evidence_due_by")
        })
        return _obj


