# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.3.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from conekta.models.charge_response_channel import ChargeResponseChannel
from conekta.models.charge_response_payment_method import ChargeResponsePaymentMethod
from conekta.models.charge_response_refunds import ChargeResponseRefunds
from conekta.models.chargeback_response import ChargebackResponse
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ChargesDataResponse(BaseModel):
    """
    ChargesDataResponse
    """ # noqa: E501
    amount: StrictInt = Field(json_schema_extra={"examples": [4321]})
    channel: Optional[ChargeResponseChannel] = None
    created_at: StrictInt = Field(json_schema_extra={"examples": [1676386026]})
    currency: StrictStr = Field(json_schema_extra={"examples": ["MXN"]})
    customer_id: Optional[StrictStr] = None
    description: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Payment from order"]})
    device_fingerprint: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["6FR3chaU4Y1nGAW5NAGd1rcjAKa142Ba"]})
    failure_code: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["suspected_fraud"]})
    failure_message: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Este cargo ha sido declinado porque el comportamiento del comprador es sospechoso."]})
    id: StrictStr = Field(description="Charge ID", json_schema_extra={"examples": ["63efa757cf65380001aec040"]})
    livemode: StrictBool = Field(description="Whether the charge was made in live mode or not", json_schema_extra={"examples": [False]})
    object: StrictStr = Field(json_schema_extra={"examples": ["charge"]})
    order_id: StrictStr = Field(description="Order ID", json_schema_extra={"examples": ["ord_2tN73UdUSNrYRPD9r"]})
    paid_at: Optional[StrictInt] = Field(default=None, description="charge Payment date", json_schema_extra={"examples": [1676390742]})
    payment_method: Optional[ChargeResponsePaymentMethod] = None
    reference_id: Optional[StrictStr] = Field(default=None, description="Reference ID of the charge", json_schema_extra={"examples": ["ref_2tN73UdUSNrYRPD9r"]})
    refunds: Optional[ChargeResponseRefunds] = None
    chargeback: Optional[ChargebackResponse] = None
    status: StrictStr = Field(description="Charge status", json_schema_extra={"examples": ["pending_payment"]})
    __properties: ClassVar[List[str]] = ["amount", "channel", "created_at", "currency", "customer_id", "description", "device_fingerprint", "failure_code", "failure_message", "id", "livemode", "object", "order_id", "paid_at", "payment_method", "reference_id", "refunds", "chargeback", "status"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChargesDataResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of channel
        if self.channel:
            _dict['channel'] = self.channel.to_dict()
        # override the default output from pydantic by calling `to_dict()` of payment_method
        if self.payment_method:
            _dict['payment_method'] = self.payment_method.to_dict()
        # override the default output from pydantic by calling `to_dict()` of refunds
        if self.refunds:
            _dict['refunds'] = self.refunds.to_dict()
        # override the default output from pydantic by calling `to_dict()` of chargeback
        if self.chargeback:
            _dict['chargeback'] = self.chargeback.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChargesDataResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount": obj.get("amount"),
            "channel": ChargeResponseChannel.from_dict(obj["channel"]) if obj.get("channel") is not None else None,
            "created_at": obj.get("created_at"),
            "currency": obj.get("currency"),
            "customer_id": obj.get("customer_id"),
            "description": obj.get("description"),
            "device_fingerprint": obj.get("device_fingerprint"),
            "failure_code": obj.get("failure_code"),
            "failure_message": obj.get("failure_message"),
            "id": obj.get("id"),
            "livemode": obj.get("livemode"),
            "object": obj.get("object"),
            "order_id": obj.get("order_id"),
            "paid_at": obj.get("paid_at"),
            "payment_method": ChargeResponsePaymentMethod.from_dict(obj["payment_method"]) if obj.get("payment_method") is not None else None,
            "reference_id": obj.get("reference_id"),
            "refunds": ChargeResponseRefunds.from_dict(obj["refunds"]) if obj.get("refunds") is not None else None,
            "chargeback": ChargebackResponse.from_dict(obj["chargeback"]) if obj.get("chargeback") is not None else None,
            "status": obj.get("status")
        })
        return _obj


