# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.3.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CheckoutResponse(BaseModel):
    """
    checkout response
    """ # noqa: E501
    allowed_payment_methods: Optional[List[StrictStr]] = Field(default=None, description="Are the payment methods available for this link", json_schema_extra={"examples": [["cash", "card", "bank_transfer", "bnpl", "pay_by_bank"]]})
    excluded_payment_methods: Optional[List[StrictStr]] = Field(default=None, description="Payment methods excluded from the checkout. This field is only returned when excluded_payment_methods is provided in the request.", json_schema_extra={"examples": [["cash", "bank_transfer"]]})
    plan_ids: Optional[List[StrictStr]] = Field(default=None, description="List of plan IDs that are available for subscription", json_schema_extra={"examples": [["plan_123", "plan_456"]]})
    can_not_expire: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    emails_sent: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [0]})
    exclude_card_networks: Optional[List[StrictStr]] = Field(default=None, json_schema_extra={"examples": [["visa", "amex"]]})
    expires_at: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1680397724]})
    failure_url: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["https://pay.conekta.com/failure"]})
    force_3ds_flow: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    id: StrictStr = Field(json_schema_extra={"examples": ["b0bf16c4-18b9-445e-ba24-01604f329dbf"]})
    livemode: StrictBool = Field(json_schema_extra={"examples": [True]})
    metadata: Optional[Dict[str, Any]] = Field(default=None, json_schema_extra={"examples": [{"key": "value"}]})
    monthly_installments_enabled: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    monthly_installments_options: Optional[List[StrictInt]] = Field(default=None, json_schema_extra={"examples": [[3, 6, 12]]})
    name: StrictStr = Field(description="Reason for charge", json_schema_extra={"examples": ["Payment Link Name 1594138857"]})
    needs_shipping_contact: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    object: StrictStr = Field(json_schema_extra={"examples": ["checkout"]})
    paid_payments_count: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [0]})
    payments_limit_count: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [5]})
    recurrent: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    slug: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["b0bf16c418b9445eba2401604f329dbf"]})
    sms_sent: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [0]})
    starts_at: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1677650400]})
    status: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Issued"]})
    success_url: Optional[StrictStr] = Field(default=None, description="The URL to redirect to after a successful payment.", json_schema_extra={"examples": ["https://pay.conekta.com/success"]})
    type: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["PaymentLink"]})
    url: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["https://pay.conekta.com/link/b0bf16c418b9445eba2401604f329dbf"]})
    __properties: ClassVar[List[str]] = ["allowed_payment_methods", "excluded_payment_methods", "plan_ids", "can_not_expire", "emails_sent", "exclude_card_networks", "expires_at", "failure_url", "force_3ds_flow", "id", "livemode", "metadata", "monthly_installments_enabled", "monthly_installments_options", "name", "needs_shipping_contact", "object", "paid_payments_count", "payments_limit_count", "recurrent", "slug", "sms_sent", "starts_at", "status", "success_url", "type", "url"]

    @field_validator('excluded_payment_methods')
    def excluded_payment_methods_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['cash', 'card', 'bank_transfer', 'bnpl', 'pay_by_bank']):
                raise ValueError("each list item must be one of ('cash', 'card', 'bank_transfer', 'bnpl', 'pay_by_bank')")
        return value

    @field_validator('exclude_card_networks')
    def exclude_card_networks_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['visa', 'mastercard', 'amex']):
                raise ValueError("each list item must be one of ('visa', 'mastercard', 'amex')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CheckoutResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CheckoutResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allowed_payment_methods": obj.get("allowed_payment_methods"),
            "excluded_payment_methods": obj.get("excluded_payment_methods"),
            "plan_ids": obj.get("plan_ids"),
            "can_not_expire": obj.get("can_not_expire"),
            "emails_sent": obj.get("emails_sent"),
            "exclude_card_networks": obj.get("exclude_card_networks"),
            "expires_at": obj.get("expires_at"),
            "failure_url": obj.get("failure_url"),
            "force_3ds_flow": obj.get("force_3ds_flow"),
            "id": obj.get("id"),
            "livemode": obj.get("livemode"),
            "metadata": obj.get("metadata"),
            "monthly_installments_enabled": obj.get("monthly_installments_enabled"),
            "monthly_installments_options": obj.get("monthly_installments_options"),
            "name": obj.get("name"),
            "needs_shipping_contact": obj.get("needs_shipping_contact"),
            "object": obj.get("object"),
            "paid_payments_count": obj.get("paid_payments_count"),
            "payments_limit_count": obj.get("payments_limit_count"),
            "recurrent": obj.get("recurrent"),
            "slug": obj.get("slug"),
            "sms_sent": obj.get("sms_sent"),
            "starts_at": obj.get("starts_at"),
            "status": obj.get("status"),
            "success_url": obj.get("success_url"),
            "type": obj.get("type"),
            "url": obj.get("url")
        })
        return _obj


