# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.3.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from conekta.models.company_document_response import CompanyDocumentResponse
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CompanyResponse(BaseModel):
    """
    CompanyResponse
    """ # noqa: E501
    id: StrictStr = Field(description="The unique identifier for the company.", json_schema_extra={"examples": ["6827305a1ec60400015eb116"]})
    name: StrictStr = Field(description="The name of the company.", json_schema_extra={"examples": ["test"]})
    active: StrictBool = Field(description="Indicates if the company is active.", json_schema_extra={"examples": [False]})
    account_status: StrictStr = Field(description="The current status of the company's account.", json_schema_extra={"examples": ["signed_up"]})
    parent_company_id: Optional[StrictStr] = Field(default=None, description="The identifier of the parent company, if any.", json_schema_extra={"examples": ["680bf1da38716d00013543bc"]})
    onboarding_status: StrictStr = Field(description="The current status of the company's onboarding process.", json_schema_extra={"examples": ["pending"]})
    documents: List[CompanyDocumentResponse] = Field(description="A list of documents related to the company.")
    created_at: StrictInt = Field(description="Timestamp of when the company was created.", json_schema_extra={"examples": [1748968241]})
    object: StrictStr = Field(description="The type of object, typically \"company\".", json_schema_extra={"examples": ["company"]})
    three_ds_enabled: Optional[StrictBool] = Field(default=None, description="Indicates if 3DS authentication is enabled for the company.", json_schema_extra={"examples": [True]})
    three_ds_mode: Optional[StrictStr] = Field(default=None, description="The 3DS mode for the company, either 'smart' or 'strict'. This property is only applicable when three_ds_enabled is true. When three_ds_enabled is false, this field will be null.", json_schema_extra={"examples": ["strict"]})
    __properties: ClassVar[List[str]] = ["id", "name", "active", "account_status", "parent_company_id", "onboarding_status", "documents", "created_at", "object", "three_ds_enabled", "three_ds_mode"]

    @field_validator('three_ds_mode')
    def three_ds_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['smart', 'strict']):
            raise ValueError("must be one of enum values ('smart', 'strict')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompanyResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in documents (list)
        _items = []
        if self.documents:
            for _item_documents in self.documents:
                if _item_documents:
                    _items.append(_item_documents.to_dict())
            _dict['documents'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompanyResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "active": obj.get("active"),
            "account_status": obj.get("account_status"),
            "parent_company_id": obj.get("parent_company_id"),
            "onboarding_status": obj.get("onboarding_status"),
            "documents": [CompanyDocumentResponse.from_dict(_item) for _item in obj["documents"]] if obj.get("documents") is not None else None,
            "created_at": obj.get("created_at"),
            "object": obj.get("object"),
            "three_ds_enabled": obj.get("three_ds_enabled"),
            "three_ds_mode": obj.get("three_ds_mode")
        })
        return _obj


