# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.2.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from conekta.models.customer_antifraud_info_response import CustomerAntifraudInfoResponse
from conekta.models.customer_fiscal_entities_response import CustomerFiscalEntitiesResponse
from conekta.models.customer_payment_methods_response import CustomerPaymentMethodsResponse
from conekta.models.customer_response_shipping_contacts import CustomerResponseShippingContacts
from conekta.models.customer_subscription_response import CustomerSubscriptionResponse
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CustomerResponse(BaseModel):
    """
    customer response
    """ # noqa: E501
    antifraud_info: Optional[CustomerAntifraudInfoResponse] = None
    corporate: Optional[StrictBool] = Field(default=None, description="true if the customer is a company")
    created_at: StrictInt = Field(description="Creation date of the object", json_schema_extra={"examples": [1485151007]})
    custom_reference: Optional[StrictStr] = Field(default=None, description="Custom reference", json_schema_extra={"examples": ["custom_reference"]})
    date_of_birth: Optional[StrictStr] = Field(default=None, description="It is a parameter that allows to identify the date of birth of the client.", json_schema_extra={"examples": ["24/07/1992"]})
    default_fiscal_entity_id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["fis_ent_2tKqqAfqPi21oCmEJ"]})
    default_shipping_contact_id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["ship_cont_2tKZsTYcsryyu7Ah8"]})
    default_payment_source_id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["src_2tHJfJ79KyUwpxTio"]})
    email: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Felipe@gmail.com"]})
    fiscal_entities: Optional[CustomerFiscalEntitiesResponse] = None
    id: StrictStr = Field(description="Customer's ID", json_schema_extra={"examples": ["cus_2tHJfJ79KyUwpxTik"]})
    livemode: StrictBool = Field(description="true if the object exists in live mode or the value false if the object exists in test mode", json_schema_extra={"examples": [True]})
    name: StrictStr = Field(description="Customer's name", json_schema_extra={"examples": ["Felipe"]})
    national_id: Optional[StrictStr] = Field(default=None, description="It is a parameter that allows to identify the national identification number of the client.", json_schema_extra={"examples": ["HEGG560427MVZRRL04"]})
    metadata: Optional[Dict[str, Any]] = None
    object: StrictStr = Field(json_schema_extra={"examples": ["customer"]})
    payment_sources: Optional[CustomerPaymentMethodsResponse] = None
    phone: Optional[StrictStr] = Field(default=None, description="Customer's phone number", json_schema_extra={"examples": ["+5215555555555"]})
    shipping_contacts: Optional[CustomerResponseShippingContacts] = None
    subscription: Optional[CustomerSubscriptionResponse] = None
    __properties: ClassVar[List[str]] = ["antifraud_info", "corporate", "created_at", "custom_reference", "date_of_birth", "default_fiscal_entity_id", "default_shipping_contact_id", "default_payment_source_id", "email", "fiscal_entities", "id", "livemode", "name", "national_id", "metadata", "object", "payment_sources", "phone", "shipping_contacts", "subscription"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomerResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of antifraud_info
        if self.antifraud_info:
            _dict['antifraud_info'] = self.antifraud_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fiscal_entities
        if self.fiscal_entities:
            _dict['fiscal_entities'] = self.fiscal_entities.to_dict()
        # override the default output from pydantic by calling `to_dict()` of payment_sources
        if self.payment_sources:
            _dict['payment_sources'] = self.payment_sources.to_dict()
        # override the default output from pydantic by calling `to_dict()` of shipping_contacts
        if self.shipping_contacts:
            _dict['shipping_contacts'] = self.shipping_contacts.to_dict()
        # override the default output from pydantic by calling `to_dict()` of subscription
        if self.subscription:
            _dict['subscription'] = self.subscription.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomerResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "antifraud_info": CustomerAntifraudInfoResponse.from_dict(obj["antifraud_info"]) if obj.get("antifraud_info") is not None else None,
            "corporate": obj.get("corporate"),
            "created_at": obj.get("created_at"),
            "custom_reference": obj.get("custom_reference"),
            "date_of_birth": obj.get("date_of_birth"),
            "default_fiscal_entity_id": obj.get("default_fiscal_entity_id"),
            "default_shipping_contact_id": obj.get("default_shipping_contact_id"),
            "default_payment_source_id": obj.get("default_payment_source_id"),
            "email": obj.get("email"),
            "fiscal_entities": CustomerFiscalEntitiesResponse.from_dict(obj["fiscal_entities"]) if obj.get("fiscal_entities") is not None else None,
            "id": obj.get("id"),
            "livemode": obj.get("livemode"),
            "name": obj.get("name"),
            "national_id": obj.get("national_id"),
            "metadata": obj.get("metadata"),
            "object": obj.get("object"),
            "payment_sources": CustomerPaymentMethodsResponse.from_dict(obj["payment_sources"]) if obj.get("payment_sources") is not None else None,
            "phone": obj.get("phone"),
            "shipping_contacts": CustomerResponseShippingContacts.from_dict(obj["shipping_contacts"]) if obj.get("shipping_contacts") is not None else None,
            "subscription": CustomerSubscriptionResponse.from_dict(obj["subscription"]) if obj.get("subscription") is not None else None
        })
        return _obj


