# coding: utf-8

"""
    Conekta API

    Conekta sdk  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Contact: engineering@conekta.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Any, List, Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, validator
from conekta.models.payment_method_card_request import PaymentMethodCardRequest
from conekta.models.payment_method_cash_request import PaymentMethodCashRequest
from conekta.models.payment_method_spei_request import PaymentMethodSpeiRequest
from typing import Any, List
from pydantic import StrictStr, Field

CUSTOMERPAYMENTMETHODSREQUEST_ONE_OF_SCHEMAS = ["PaymentMethodCardRequest", "PaymentMethodCashRequest", "PaymentMethodSpeiRequest"]

class CustomerPaymentMethodsRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    # data type: PaymentMethodCardRequest
    oneof_schema_1_validator: Optional[PaymentMethodCardRequest] = None
    # data type: PaymentMethodCashRequest
    oneof_schema_2_validator: Optional[PaymentMethodCashRequest] = None
    # data type: PaymentMethodSpeiRequest
    oneof_schema_3_validator: Optional[PaymentMethodSpeiRequest] = None
    actual_instance: Any
    one_of_schemas: List[str] = Field(CUSTOMERPAYMENTMETHODSREQUEST_ONE_OF_SCHEMAS, const=True)

    class Config:
        validate_assignment = True

    @validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = cls()
        error_messages = []
        match = 0
        # validate data type: PaymentMethodCardRequest
        if type(v) is not PaymentMethodCardRequest:
            error_messages.append(f"Error! Input type `{type(v)}` is not `PaymentMethodCardRequest`")
        else:
            match += 1

        # validate data type: PaymentMethodCashRequest
        if type(v) is not PaymentMethodCashRequest:
            error_messages.append(f"Error! Input type `{type(v)}` is not `PaymentMethodCashRequest`")
        else:
            match += 1

        # validate data type: PaymentMethodSpeiRequest
        if type(v) is not PaymentMethodSpeiRequest:
            error_messages.append(f"Error! Input type `{type(v)}` is not `PaymentMethodSpeiRequest`")
        else:
            match += 1

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into CustomerPaymentMethodsRequest with oneOf schemas: PaymentMethodCardRequest, PaymentMethodCashRequest, PaymentMethodSpeiRequest. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into CustomerPaymentMethodsRequest with oneOf schemas: PaymentMethodCardRequest, PaymentMethodCashRequest, PaymentMethodSpeiRequest. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> CustomerPaymentMethodsRequest:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> CustomerPaymentMethodsRequest:
        """Returns the object represented by the json string"""
        instance = cls()
        error_messages = []
        match = 0

        # deserialize data into PaymentMethodCardRequest
        try:
            instance.actual_instance = PaymentMethodCardRequest.from_json(json_str)
            match += 1
        except ValidationError as e:
            error_messages.append(str(e))
        # deserialize data into PaymentMethodCashRequest
        try:
            instance.actual_instance = PaymentMethodCashRequest.from_json(json_str)
            match += 1
        except ValidationError as e:
            error_messages.append(str(e))
        # deserialize data into PaymentMethodSpeiRequest
        try:
            instance.actual_instance = PaymentMethodSpeiRequest.from_json(json_str)
            match += 1
        except ValidationError as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into CustomerPaymentMethodsRequest with oneOf schemas: PaymentMethodCardRequest, PaymentMethodCashRequest, PaymentMethodSpeiRequest. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into CustomerPaymentMethodsRequest with oneOf schemas: PaymentMethodCardRequest, PaymentMethodCashRequest, PaymentMethodSpeiRequest. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is not None:
            return self.actual_instance.to_json()
        else:
            return "null"

    def to_dict(self) -> dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is not None:
            return self.actual_instance.to_dict()
        else:
            return dict()

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.dict())

