# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.2.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from conekta.models.customer_details import CustomerDetails
from conekta.models.subscription_details import SubscriptionDetails
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CustomerPortalResponse(BaseModel):
    """
    Customer portal model
    """ # noqa: E501
    slug: Optional[StrictStr] = Field(default=None, description="Unique slug identifier for the portal", json_schema_extra={"examples": ["agIvD4QSBl4Nunq4TmuozMw2ThtyVC"]})
    subscription_id: Optional[StrictStr] = Field(default=None, description="Associated subscription ID", json_schema_extra={"examples": ["sub_2yYsQuYtXAbP1fdYu"]})
    customer_id: Optional[StrictStr] = Field(default=None, description="Associated customer ID", json_schema_extra={"examples": ["cus_2yDzKtEAD3khH8Sga"]})
    livemode: Optional[StrictBool] = Field(default=None, description="Whether this is a live or test mode portal", json_schema_extra={"examples": [False]})
    subscription: Optional[SubscriptionDetails] = None
    customer: Optional[CustomerDetails] = None
    id: Optional[StrictStr] = Field(default=None, description="Customer portal ID", json_schema_extra={"examples": ["scp_2ym7QbU9dTh7Froti"]})
    company_id: Optional[StrictStr] = Field(default=None, description="Associated company ID", json_schema_extra={"examples": ["63dad459920de10001d177b3"]})
    object: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["customer_portal"]})
    created_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp of creation", json_schema_extra={"examples": [1759108828]})
    updated_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp of last update", json_schema_extra={"examples": [1759108828]})
    portal_url: Optional[StrictStr] = Field(default=None, description="URL to access the customer portal", json_schema_extra={"examples": ["https://pay.stg.conekta.io/subscription/management/agIvD4QSBl4Nunq4TmuozMw2ThtyVC"]})
    __properties: ClassVar[List[str]] = ["slug", "subscription_id", "customer_id", "livemode", "subscription", "customer", "id", "company_id", "object", "created_at", "updated_at", "portal_url"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomerPortalResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of subscription
        if self.subscription:
            _dict['subscription'] = self.subscription.to_dict()
        # override the default output from pydantic by calling `to_dict()` of customer
        if self.customer:
            _dict['customer'] = self.customer.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomerPortalResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "slug": obj.get("slug"),
            "subscription_id": obj.get("subscription_id"),
            "customer_id": obj.get("customer_id"),
            "livemode": obj.get("livemode"),
            "subscription": SubscriptionDetails.from_dict(obj["subscription"]) if obj.get("subscription") is not None else None,
            "customer": CustomerDetails.from_dict(obj["customer"]) if obj.get("customer") is not None else None,
            "id": obj.get("id"),
            "company_id": obj.get("company_id"),
            "object": obj.get("object"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "portal_url": obj.get("portal_url")
        })
        return _obj


