# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.2.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CustomerSubscriptionResponse(BaseModel):
    """
    subscription model
    """ # noqa: E501
    billing_cycle_start: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1677626827]})
    billing_cycle_end: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1677626827]})
    canceled_at: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1678258162]})
    canceled_reason: Optional[StrictStr] = Field(default=None, description="Reason for cancellation. This field appears when the subscription status is 'canceled'.", json_schema_extra={"examples": ["user_cancelation"]})
    card_id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["src_2tKcHxhTz7xU5SymL"]})
    charge_id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["2tKcHxhTz7xU5SymL"]})
    created_at: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1677626837]})
    customer_custom_reference: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["dotnet_123456"]})
    customer_id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["cus_2tKcHxhTz7xU5SymF"]})
    id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["gold-plan"]})
    last_billing_cycle_order_id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["ord_2tSoMP7bZJbLiq4z8"]})
    object: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["subscription"]})
    paused_at: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1678258162]})
    plan_id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["plan_2tXx672QLQ68CkmMn"]})
    status: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["past_due"]})
    subscription_start: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1677626837]})
    trial_start: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1677626837]})
    trial_end: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1677626837]})
    __properties: ClassVar[List[str]] = ["billing_cycle_start", "billing_cycle_end", "canceled_at", "canceled_reason", "card_id", "charge_id", "created_at", "customer_custom_reference", "customer_id", "id", "last_billing_cycle_order_id", "object", "paused_at", "plan_id", "status", "subscription_start", "trial_start", "trial_end"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomerSubscriptionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomerSubscriptionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "billing_cycle_start": obj.get("billing_cycle_start"),
            "billing_cycle_end": obj.get("billing_cycle_end"),
            "canceled_at": obj.get("canceled_at"),
            "canceled_reason": obj.get("canceled_reason"),
            "card_id": obj.get("card_id"),
            "charge_id": obj.get("charge_id"),
            "created_at": obj.get("created_at"),
            "customer_custom_reference": obj.get("customer_custom_reference"),
            "customer_id": obj.get("customer_id"),
            "id": obj.get("id"),
            "last_billing_cycle_order_id": obj.get("last_billing_cycle_order_id"),
            "object": obj.get("object"),
            "paused_at": obj.get("paused_at"),
            "plan_id": obj.get("plan_id"),
            "status": obj.get("status"),
            "subscription_start": obj.get("subscription_start"),
            "trial_start": obj.get("trial_start"),
            "trial_end": obj.get("trial_end")
        })
        return _obj


