# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.3.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from conekta.models.customer_shipping_contacts_request_address import CustomerShippingContactsRequestAddress
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CustomerShippingContactsDataResponse(BaseModel):
    """
    CustomerShippingContactsDataResponse
    """ # noqa: E501
    phone: Optional[StrictStr] = Field(default=None, description="Phone contact", json_schema_extra={"examples": ["+525511223344"]})
    receiver: Optional[StrictStr] = Field(default=None, description="Name of the person who will receive the order", json_schema_extra={"examples": ["Marvin Fuller"]})
    between_streets: Optional[StrictStr] = Field(default=None, description="The street names between which the order will be delivered.", json_schema_extra={"examples": ["Ackerman Crescent"]})
    address: CustomerShippingContactsRequestAddress
    parent_id: Optional[StrictStr] = None
    default: Optional[StrictBool] = None
    deleted: Optional[StrictBool] = None
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Metadata associated with the shipping contact")
    id: StrictStr = Field(json_schema_extra={"examples": ["ship_cont_2tKZsTYcsryyu7Ah8"]})
    object: StrictStr = Field(json_schema_extra={"examples": ["shipping_contact"]})
    created_at: StrictInt = Field(json_schema_extra={"examples": [1675715413]})
    __properties: ClassVar[List[str]] = ["phone", "receiver", "between_streets", "address", "parent_id", "default", "deleted", "metadata", "id", "object", "created_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomerShippingContactsDataResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomerShippingContactsDataResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "phone": obj.get("phone"),
            "receiver": obj.get("receiver"),
            "between_streets": obj.get("between_streets"),
            "address": CustomerShippingContactsRequestAddress.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "parent_id": obj.get("parent_id"),
            "default": obj.get("default"),
            "deleted": obj.get("deleted"),
            "metadata": obj.get("metadata"),
            "id": obj.get("id"),
            "object": obj.get("object"),
            "created_at": obj.get("created_at")
        })
        return _obj


