# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.3.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OrderResponseCheckout(BaseModel):
    """
    OrderResponseCheckout
    """ # noqa: E501
    allowed_payment_methods: Optional[List[StrictStr]] = Field(default=None, description="Are the payment methods available for this link", json_schema_extra={"examples": [["cash", "card", "bank_transfer", "bnpl", "pay_by_bank", "apple", "google"]]})
    excluded_payment_methods: Optional[List[StrictStr]] = Field(default=None, description="Payment methods excluded from the checkout. This field is only returned when excluded_payment_methods is provided in the request.", json_schema_extra={"examples": [["cash", "bank_transfer"]]})
    can_not_expire: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    emails_sent: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [0]})
    exclude_card_networks: Optional[List[StrictStr]] = Field(default=None, json_schema_extra={"examples": [["visa", "amex"]]})
    expires_at: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1676613599]})
    failure_url: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["http://187.216.228.66:2222/SysVentasPagos/Acceso.aspx"]})
    force_3ds_flow: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    force_save_card: Optional[StrictBool] = Field(default=None, description="Indicates whether the card used for the payment should be saved for future purchases. This field is only applicable for card payments.", json_schema_extra={"examples": [False]})
    id: StrictStr = Field(json_schema_extra={"examples": ["6fca054a-8519-4c43-971e-cea35cc519bb"]})
    is_redirect_on_failure: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    livemode: StrictBool = Field(json_schema_extra={"examples": [False]})
    max_failed_retries: Optional[StrictInt] = Field(default=None, description="Number of retries allowed before the checkout is marked as failed", json_schema_extra={"examples": [3]})
    metadata: Optional[Dict[str, Any]] = None
    monthly_installments_enabled: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    monthly_installments_options: Optional[List[StrictInt]] = None
    name: StrictStr = Field(json_schema_extra={"examples": ["ord-2tNDzhA4Akmzj11AS"]})
    needs_shipping_contact: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    object: StrictStr = Field(json_schema_extra={"examples": ["checkout"]})
    on_demand_enabled: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [True]})
    paid_payments_count: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [0]})
    recurrent: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    redirection_time: Optional[StrictInt] = Field(default=None, description="number of seconds to wait before redirecting to the success_url", json_schema_extra={"examples": [2]})
    slug: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["6fca054a85194c43971ecea35cc519bb"]})
    sms_sent: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [0]})
    success_url: Optional[StrictStr] = Field(default=None, description="Redirection url back to the site in case of successful payment, applies only to HostedPayment", json_schema_extra={"examples": ["http://187.216.228.66:2222/SysVentasPagos/Acceso.aspx"]})
    starts_at: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1676354400]})
    status: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Issued"]})
    type: StrictStr = Field(description="This field represents the type of checkout, which determines the user experience during the payment process. 'HostedPayment' will redirect the customer to a Conekta-hosted page to complete the payment, while 'Integration' allows the payment process to be handled entirely on your site using Conekta's APIs and SDKs.", json_schema_extra={"examples": ["HostedPayment"]})
    url: Optional[StrictStr] = Field(default=None, description="Indicate the url of the Conekta component to complete the payment. For HostedPayment, this will be a Conekta-hosted page", json_schema_extra={"examples": ["https://pay.conekta.io/checkout/6fca054a85194c43971ecea35cc519bb"]})
    __properties: ClassVar[List[str]] = ["allowed_payment_methods", "excluded_payment_methods", "can_not_expire", "emails_sent", "exclude_card_networks", "expires_at", "failure_url", "force_3ds_flow", "force_save_card", "id", "is_redirect_on_failure", "livemode", "max_failed_retries", "metadata", "monthly_installments_enabled", "monthly_installments_options", "name", "needs_shipping_contact", "object", "on_demand_enabled", "paid_payments_count", "recurrent", "redirection_time", "slug", "sms_sent", "success_url", "starts_at", "status", "type", "url"]

    @field_validator('excluded_payment_methods')
    def excluded_payment_methods_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['cash', 'card', 'bank_transfer', 'bnpl', 'pay_by_bank']):
                raise ValueError("each list item must be one of ('cash', 'card', 'bank_transfer', 'bnpl', 'pay_by_bank')")
        return value

    @field_validator('exclude_card_networks')
    def exclude_card_networks_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['visa', 'mastercard', 'amex']):
                raise ValueError("each list item must be one of ('visa', 'mastercard', 'amex')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrderResponseCheckout from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrderResponseCheckout from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allowed_payment_methods": obj.get("allowed_payment_methods"),
            "excluded_payment_methods": obj.get("excluded_payment_methods"),
            "can_not_expire": obj.get("can_not_expire"),
            "emails_sent": obj.get("emails_sent"),
            "exclude_card_networks": obj.get("exclude_card_networks"),
            "expires_at": obj.get("expires_at"),
            "failure_url": obj.get("failure_url"),
            "force_3ds_flow": obj.get("force_3ds_flow"),
            "force_save_card": obj.get("force_save_card"),
            "id": obj.get("id"),
            "is_redirect_on_failure": obj.get("is_redirect_on_failure"),
            "livemode": obj.get("livemode"),
            "max_failed_retries": obj.get("max_failed_retries"),
            "metadata": obj.get("metadata"),
            "monthly_installments_enabled": obj.get("monthly_installments_enabled"),
            "monthly_installments_options": obj.get("monthly_installments_options"),
            "name": obj.get("name"),
            "needs_shipping_contact": obj.get("needs_shipping_contact"),
            "object": obj.get("object"),
            "on_demand_enabled": obj.get("on_demand_enabled"),
            "paid_payments_count": obj.get("paid_payments_count"),
            "recurrent": obj.get("recurrent"),
            "redirection_time": obj.get("redirection_time"),
            "slug": obj.get("slug"),
            "sms_sent": obj.get("sms_sent"),
            "success_url": obj.get("success_url"),
            "starts_at": obj.get("starts_at"),
            "status": obj.get("status"),
            "type": obj.get("type"),
            "url": obj.get("url")
        })
        return _obj


