# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.2.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OrderResponseCustomerInfo(BaseModel):
    """
    OrderResponseCustomerInfo
    """ # noqa: E501
    object: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["customer_info"]})
    customer_custom_reference: Optional[StrictStr] = Field(default=None, description="Custom reference", json_schema_extra={"examples": ["custom_reference"]})
    name: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["DevTest"]})
    email: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["test@conekta.com"]})
    phone: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["5522997233"]})
    corporate: Optional[StrictBool] = False
    customer_id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["cus_23874283647"]})
    __properties: ClassVar[List[str]] = ["object", "customer_custom_reference", "name", "email", "phone", "corporate", "customer_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrderResponseCustomerInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrderResponseCustomerInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "object": obj.get("object"),
            "customer_custom_reference": obj.get("customer_custom_reference"),
            "name": obj.get("name"),
            "email": obj.get("email"),
            "phone": obj.get("phone"),
            "corporate": obj.get("corporate") if obj.get("corporate") is not None else False,
            "customer_id": obj.get("customer_id")
        })
        return _obj


