# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.3.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from conekta.models.order_fiscal_entity_address_response import OrderFiscalEntityAddressResponse
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OrderFiscalEntityResponse(BaseModel):
    """
    Fiscal entity of the order, Currently it is a purely informative field
    """ # noqa: E501
    address: OrderFiscalEntityAddressResponse
    email: Optional[StrictStr] = Field(default=None, description="Email of the fiscal entity", json_schema_extra={"examples": ["test@gmail.com"]})
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Metadata associated with the fiscal entity")
    name: Optional[StrictStr] = Field(default=None, description="Name of the fiscal entity", json_schema_extra={"examples": ["Conekta Inc"]})
    tax_id: Optional[StrictStr] = Field(default=None, description="Tax ID of the fiscal entity", json_schema_extra={"examples": ["324234234"]})
    id: StrictStr = Field(description="ID of the fiscal entity", json_schema_extra={"examples": ["fis_ent_2tN85VYaSMyDvjB3M"]})
    created_at: StrictInt = Field(description="The time at which the object was created in seconds since the Unix epoch", json_schema_extra={"examples": [1676328434]})
    object: StrictStr = Field(json_schema_extra={"examples": ["fiscal_entity"]})
    phone: Optional[StrictStr] = Field(default=None, description="Phone of the fiscal entity", json_schema_extra={"examples": ["+525511223344"]})
    __properties: ClassVar[List[str]] = ["address", "email", "metadata", "name", "tax_id", "id", "created_at", "object", "phone"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrderFiscalEntityResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrderFiscalEntityResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": OrderFiscalEntityAddressResponse.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "email": obj.get("email"),
            "metadata": obj.get("metadata"),
            "name": obj.get("name"),
            "tax_id": obj.get("tax_id"),
            "id": obj.get("id"),
            "created_at": obj.get("created_at"),
            "object": obj.get("object"),
            "phone": obj.get("phone")
        })
        return _obj


