# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.3.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OrderCheckoutRequest(BaseModel):
    """
    [Checkout](https://developers.conekta.com/v2.3.0/reference/payment-link) details 
    """ # noqa: E501
    allowed_payment_methods: Optional[List[StrictStr]] = Field(default=None, description="Are the payment methods available for this link. For subscriptions, only 'card' is allowed due to the recurring nature of the payments. This field is mutually exclusive with excluded_payment_methods.", json_schema_extra={"examples": [["cash", "card", "bank_transfer", "bnpl", "pay_by_bank", "apple", "google"]]})
    excluded_payment_methods: Optional[List[StrictStr]] = Field(default=None, description="Payment methods to be excluded from the checkout. This field is mutually exclusive with allowed_payment_methods.", json_schema_extra={"examples": [["cash", "bank_transfer"]]})
    exclude_card_networks: Optional[List[StrictStr]] = Field(default=None, description="List of card networks to exclude from the checkout. This field is only applicable for card payments.", json_schema_extra={"examples": [["visa", "amex"]]})
    plan_ids: Optional[List[StrictStr]] = Field(default=None, description="List of plan IDs that will be available for subscription. This field is required for subscription payments.", json_schema_extra={"examples": [["plan_123", "plan_456"]]})
    expires_at: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="It is the time when the link will expire.  It is expressed in seconds since the Unix epoch. The valid range is from 5 minutes to 365 days from the creation date. ")
    failure_url: Optional[StrictStr] = Field(default=None, description="Redirection url back to the site in case of failed payment, applies only to HostedPayment.", json_schema_extra={"examples": ["https://www.mysite.com/failure"]})
    force_save_card: Optional[StrictBool] = Field(default=None, description="Indicates whether the card used for the payment should be saved for future purchases. This field is only applicable for card payments.", json_schema_extra={"examples": [False]})
    monthly_installments_enabled: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    monthly_installments_options: Optional[List[StrictInt]] = Field(default=None, json_schema_extra={"examples": [[3, 6, 12]]})
    max_failed_retries: Optional[StrictInt] = Field(default=None, description="Number of retries allowed before the checkout is marked as failed", json_schema_extra={"examples": [3]})
    name: Optional[StrictStr] = Field(default=None, description="Reason for payment")
    on_demand_enabled: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [True]})
    redirection_time: Optional[StrictInt] = Field(default=None, description="number of seconds to wait before redirecting to the success_url", json_schema_extra={"examples": [10]})
    success_url: Optional[StrictStr] = Field(default=None, description="Redirection url back to the site in case of successful payment, applies only to HostedPayment", json_schema_extra={"examples": ["https://www.mysite.com/success"]})
    type: Optional[StrictStr] = Field(default=None, description="Required. This field represents the type of checkout, which determines the user experience during the payment process. 'HostedPayment' will redirect the customer to a Conekta-hosted page to complete the payment, while 'Integration' allows the payment process to be handled entirely on your site using Conekta's APIs and SDKs.")
    __properties: ClassVar[List[str]] = ["allowed_payment_methods", "excluded_payment_methods", "exclude_card_networks", "plan_ids", "expires_at", "failure_url", "force_save_card", "monthly_installments_enabled", "monthly_installments_options", "max_failed_retries", "name", "on_demand_enabled", "redirection_time", "success_url", "type"]

    @field_validator('allowed_payment_methods')
    def allowed_payment_methods_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['cash', 'card', 'bank_transfer', 'bnpl', 'pay_by_bank', 'apple', 'google']):
                raise ValueError("each list item must be one of ('cash', 'card', 'bank_transfer', 'bnpl', 'pay_by_bank', 'apple', 'google')")
        return value

    @field_validator('excluded_payment_methods')
    def excluded_payment_methods_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['cash', 'card', 'bank_transfer', 'bnpl', 'pay_by_bank']):
                raise ValueError("each list item must be one of ('cash', 'card', 'bank_transfer', 'bnpl', 'pay_by_bank')")
        return value

    @field_validator('exclude_card_networks')
    def exclude_card_networks_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['visa', 'mastercard', 'amex']):
                raise ValueError("each list item must be one of ('visa', 'mastercard', 'amex')")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Integration', 'HostedPayment']):
            raise ValueError("must be one of enum values ('Integration', 'HostedPayment')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrderCheckoutRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrderCheckoutRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allowed_payment_methods": obj.get("allowed_payment_methods"),
            "excluded_payment_methods": obj.get("excluded_payment_methods"),
            "exclude_card_networks": obj.get("exclude_card_networks"),
            "plan_ids": obj.get("plan_ids"),
            "expires_at": obj.get("expires_at"),
            "failure_url": obj.get("failure_url"),
            "force_save_card": obj.get("force_save_card"),
            "monthly_installments_enabled": obj.get("monthly_installments_enabled"),
            "monthly_installments_options": obj.get("monthly_installments_options"),
            "max_failed_retries": obj.get("max_failed_retries"),
            "name": obj.get("name"),
            "on_demand_enabled": obj.get("on_demand_enabled"),
            "redirection_time": obj.get("redirection_time"),
            "success_url": obj.get("success_url"),
            "type": obj.get("type")
        })
        return _obj


