# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.3.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PaymentMethodCash(BaseModel):
    """
    PaymentMethodCash
    """ # noqa: E501
    type: Optional[StrictStr] = None
    object: StrictStr = Field(json_schema_extra={"examples": ["payment_source"]})
    agreement: Optional[StrictStr] = Field(default=None, description="Agreement ID", json_schema_extra={"examples": ["agreement_2tN73UdUSNrYRPD9r"]})
    auth_code: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [542563]})
    cashier_id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["OINM01010"]})
    reference: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["93000262276908"]})
    barcode_url: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["https://barcodes.conekta.com/644ebf80f2243197aad6cd8810375b905b613dbe.png"]})
    expires_at: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [0]})
    product_type: Optional[StrictStr] = Field(default=None, description="Product type, e.g. bbva_cash_in, cash_in, pespay_cash_in, etc.", json_schema_extra={"examples": ["bbva_cash_in"]})
    service_name: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["store"]})
    store: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["10MON50EDI"]})
    store_name: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["wallmart"]})
    customer_ip_address: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["0.0.0.0"]})
    __properties: ClassVar[List[str]] = ["type", "object", "agreement", "auth_code", "cashier_id", "reference", "barcode_url", "expires_at", "product_type", "service_name", "store", "store_name", "customer_ip_address"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentMethodCash from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentMethodCash from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "object": obj.get("object"),
            "agreement": obj.get("agreement"),
            "auth_code": obj.get("auth_code"),
            "cashier_id": obj.get("cashier_id"),
            "reference": obj.get("reference"),
            "barcode_url": obj.get("barcode_url"),
            "expires_at": obj.get("expires_at"),
            "product_type": obj.get("product_type"),
            "service_name": obj.get("service_name"),
            "store": obj.get("store"),
            "store_name": obj.get("store_name"),
            "customer_ip_address": obj.get("customer_ip_address")
        })
        return _obj


