# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.2.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from conekta.models.cash_agreements_response import CashAgreementsResponse
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PaymentMethodCashRecurrentResponse(BaseModel):
    """
    Alias of cash response used when type=cash_recurrent
    """ # noqa: E501
    type: StrictStr
    id: StrictStr = Field(json_schema_extra={"examples": ["src_2s8K1B3PBKDontpi9"]})
    object: StrictStr = Field(json_schema_extra={"examples": ["payment_source"]})
    created_at: StrictInt = Field(json_schema_extra={"examples": [1675715413]})
    parent_id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["cus_2s8K1B3PBKDontpi8"]})
    agreements: Optional[List[CashAgreementsResponse]] = None
    reference: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["93000262276908"]})
    barcode: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["93000262276908"]})
    barcode_url: Optional[StrictStr] = Field(default=None, description="URL to the barcode image, reference is the same as barcode", json_schema_extra={"examples": ["https://barcodes.conekta.com/644ebf80f2243197aad6cd8810375b905b613dbe.png"]})
    expires_at: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1742483424]})
    provider: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Cash"]})
    __properties: ClassVar[List[str]] = ["type", "id", "object", "created_at", "parent_id", "agreements", "reference", "barcode", "barcode_url", "expires_at", "provider"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentMethodCashRecurrentResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in agreements (list)
        _items = []
        if self.agreements:
            for _item_agreements in self.agreements:
                if _item_agreements:
                    _items.append(_item_agreements.to_dict())
            _dict['agreements'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentMethodCashRecurrentResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "id": obj.get("id"),
            "object": obj.get("object"),
            "created_at": obj.get("created_at"),
            "parent_id": obj.get("parent_id"),
            "agreements": [CashAgreementsResponse.from_dict(_item) for _item in obj["agreements"]] if obj.get("agreements") is not None else None,
            "reference": obj.get("reference"),
            "barcode": obj.get("barcode"),
            "barcode_url": obj.get("barcode_url"),
            "expires_at": obj.get("expires_at"),
            "provider": obj.get("provider")
        })
        return _obj


