# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.3.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PaymentMethodPbbPayment(BaseModel):
    """
    PaymentMethodPbbPayment
    """ # noqa: E501
    type: Optional[StrictStr] = None
    object: StrictStr = Field(json_schema_extra={"examples": ["payment_source"]})
    deep_link: StrictStr = Field(description="Deep link for the payment, use for mobile apps/flows", json_schema_extra={"examples": ["https://mgm.bbva.mx/WA3b/pbb?AGREEMENT=002484374&AMOUNT=1&CONCEPT=PagoDirecto&CURRENCY=MXN&REFERENCE=22277523174328893295"]})
    expires_at: Annotated[int, Field(strict=True, ge=0)] = Field(description="Expiration date of the charge", json_schema_extra={"examples": [1683053729]})
    product_type: StrictStr = Field(description="Product type of the charge")
    redirect_url: StrictStr = Field(description="URL to redirect the customer to complete the payment", json_schema_extra={"examples": ["https://example.com/redirect"]})
    reference: StrictStr = Field(description="Reference for the payment", json_schema_extra={"examples": ["22277523174328893295"]})
    __properties: ClassVar[List[str]] = ["type", "object", "deep_link", "expires_at", "product_type", "redirect_url", "reference"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentMethodPbbPayment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentMethodPbbPayment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "object": obj.get("object"),
            "deep_link": obj.get("deep_link"),
            "expires_at": obj.get("expires_at"),
            "product_type": obj.get("product_type"),
            "redirect_url": obj.get("redirect_url"),
            "reference": obj.get("reference")
        })
        return _obj


