# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.2.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PaymentMethodBnplPayment(BaseModel):
    """
    PaymentMethodBnplPayment
    """ # noqa: E501
    type: Optional[StrictStr] = None
    object: StrictStr
    cancel_url: Optional[StrictStr] = Field(default=None, description="URL to redirect the customer after a canceled payment", json_schema_extra={"examples": ["https://example.com/cancel"]})
    expires_at: StrictInt = Field(description="Expiration date of the charge", json_schema_extra={"examples": [1683053729]})
    failure_url: Optional[StrictStr] = Field(default=None, description="URL to redirect the customer after a failed payment", json_schema_extra={"examples": ["https://example.com/failure"]})
    product_type: StrictStr = Field(description="Product type of the charge")
    redirect_url: Optional[StrictStr] = Field(default=None, description="URL to redirect the customer to complete the payment", json_schema_extra={"examples": ["https://example.com/redirect"]})
    success_url: Optional[StrictStr] = Field(default=None, description="URL to redirect the customer after a successful payment", json_schema_extra={"examples": ["https://example.com/success"]})
    __properties: ClassVar[List[str]] = ["type", "object", "cancel_url", "expires_at", "failure_url", "product_type", "redirect_url", "success_url"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['bnpl_payment']):
            raise ValueError("must be one of enum values ('bnpl_payment')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentMethodBnplPayment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentMethodBnplPayment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "object": obj.get("object"),
            "cancel_url": obj.get("cancel_url"),
            "expires_at": obj.get("expires_at"),
            "failure_url": obj.get("failure_url"),
            "product_type": obj.get("product_type"),
            "redirect_url": obj.get("redirect_url"),
            "success_url": obj.get("success_url")
        })
        return _obj


