# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.2.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PaymentMethodBankTransfer(BaseModel):
    """
    PaymentMethodBankTransfer
    """ # noqa: E501
    type: Optional[StrictStr] = None
    object: StrictStr = Field(json_schema_extra={"examples": ["payment_source"]})
    bank: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["STP"]})
    clabe: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["646180111805034237"]})
    description: Optional[StrictStr] = None
    executed_at: Optional[StrictStr] = None
    expires_at: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1683053729]})
    issuing_account_bank: Optional[StrictStr] = None
    issuing_account_number: Optional[StrictStr] = None
    issuing_account_holder_name: Optional[StrictStr] = None
    issuing_account_tax_id: Optional[StrictStr] = None
    payment_attempts: Optional[List[Any]] = None
    receiving_account_holder_name: Optional[StrictStr] = None
    receiving_account_number: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["646180111805034237"]})
    receiving_account_bank: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["STP"]})
    receiving_account_tax_id: Optional[StrictStr] = None
    reference_number: Optional[StrictStr] = None
    tracking_code: Optional[StrictStr] = None
    customer_ip_address: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["0.0.0.0"]})
    __properties: ClassVar[List[str]] = ["type", "object", "bank", "clabe", "description", "executed_at", "expires_at", "issuing_account_bank", "issuing_account_number", "issuing_account_holder_name", "issuing_account_tax_id", "payment_attempts", "receiving_account_holder_name", "receiving_account_number", "receiving_account_bank", "receiving_account_tax_id", "reference_number", "tracking_code", "customer_ip_address"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentMethodBankTransfer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentMethodBankTransfer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "object": obj.get("object"),
            "bank": obj.get("bank"),
            "clabe": obj.get("clabe"),
            "description": obj.get("description"),
            "executed_at": obj.get("executed_at"),
            "expires_at": obj.get("expires_at"),
            "issuing_account_bank": obj.get("issuing_account_bank"),
            "issuing_account_number": obj.get("issuing_account_number"),
            "issuing_account_holder_name": obj.get("issuing_account_holder_name"),
            "issuing_account_tax_id": obj.get("issuing_account_tax_id"),
            "payment_attempts": obj.get("payment_attempts"),
            "receiving_account_holder_name": obj.get("receiving_account_holder_name"),
            "receiving_account_number": obj.get("receiving_account_number"),
            "receiving_account_bank": obj.get("receiving_account_bank"),
            "receiving_account_tax_id": obj.get("receiving_account_tax_id"),
            "reference_number": obj.get("reference_number"),
            "tracking_code": obj.get("tracking_code"),
            "customer_ip_address": obj.get("customer_ip_address")
        })
        return _obj


