# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.3.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from conekta.models.payout import Payout
from conekta.models.payout_order_request_customer_info import PayoutOrderRequestCustomerInfo
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PayoutOrderRequest(BaseModel):
    """
    a payout order
    """ # noqa: E501
    allowed_payout_methods: List[StrictStr] = Field(description="The payout methods that are allowed for the payout order.", json_schema_extra={"examples": [["cashout"]]})
    amount: StrictInt = Field(description="The amount of the payout order.", json_schema_extra={"examples": [100]})
    currency: StrictStr = Field(description="The currency in which the payout order is made.", json_schema_extra={"examples": ["MXN"]})
    customer_info: PayoutOrderRequestCustomerInfo
    expires_at: StrictInt = Field(description="The expiration time of the payout order in Unix timestamp.", json_schema_extra={"examples": [1700000000]})
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="The metadata of the payout order.", json_schema_extra={"examples": [{"custom_client_id": "12345"}]})
    payout: Payout
    reason: StrictStr = Field(description="The reason for the payout order.", json_schema_extra={"examples": ["Payout order for the customer"]})
    __properties: ClassVar[List[str]] = ["allowed_payout_methods", "amount", "currency", "customer_info", "expires_at", "metadata", "payout", "reason"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PayoutOrderRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of customer_info
        if self.customer_info:
            _dict['customer_info'] = self.customer_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of payout
        if self.payout:
            _dict['payout'] = self.payout.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PayoutOrderRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allowed_payout_methods": obj.get("allowed_payout_methods"),
            "amount": obj.get("amount"),
            "currency": obj.get("currency") if obj.get("currency") is not None else 'MXN',
            "customer_info": PayoutOrderRequestCustomerInfo.from_dict(obj["customer_info"]) if obj.get("customer_info") is not None else None,
            "expires_at": obj.get("expires_at"),
            "metadata": obj.get("metadata"),
            "payout": Payout.from_dict(obj["payout"]) if obj.get("payout") is not None else None,
            "reason": obj.get("reason")
        })
        return _obj


