# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.3.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PlanResponse(BaseModel):
    """
    plans model
    """ # noqa: E501
    amount: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [10000]})
    created_at: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1666900846]})
    currency: Optional[Annotated[str, Field(strict=True, max_length=3)]] = Field(default=None, json_schema_extra={"examples": ["MXN"]})
    expiry_count: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [12]})
    frequency: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1]})
    id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["gold-plan"]})
    interval: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["month"]})
    livemode: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [True]})
    name: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Extra Plan3"]})
    object: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["plan"]})
    trial_period_days: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [0]})
    max_retries: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [3]})
    retry_delay_hours: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [48]})
    __properties: ClassVar[List[str]] = ["amount", "created_at", "currency", "expiry_count", "frequency", "id", "interval", "livemode", "name", "object", "trial_period_days", "max_retries", "retry_delay_hours"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlanResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlanResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount": obj.get("amount"),
            "created_at": obj.get("created_at"),
            "currency": obj.get("currency"),
            "expiry_count": obj.get("expiry_count"),
            "frequency": obj.get("frequency"),
            "id": obj.get("id"),
            "interval": obj.get("interval"),
            "livemode": obj.get("livemode"),
            "name": obj.get("name"),
            "object": obj.get("object"),
            "trial_period_days": obj.get("trial_period_days"),
            "max_retries": obj.get("max_retries"),
            "retry_delay_hours": obj.get("retry_delay_hours")
        })
        return _obj


