# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.3.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RiskRulesData(BaseModel):
    """
    RiskRulesData
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="rule id", json_schema_extra={"examples": ["618c3f2fdb8b8da9be376af9"]})
    var_field: Optional[StrictStr] = Field(default=None, description="field to be used for the rule", alias="field", json_schema_extra={"examples": ["email"]})
    created_at: Optional[StrictStr] = Field(default=None, description="rule creation date", json_schema_extra={"examples": ["2021-11-10T21:52:47.339+00:00"]})
    value: Optional[StrictStr] = Field(default=None, description="value to be used for the rule", json_schema_extra={"examples": ["email@example.com"]})
    is_global: Optional[StrictBool] = Field(default=None, description="if the rule is global", json_schema_extra={"examples": [False]})
    is_test: Optional[StrictBool] = Field(default=None, description="if the rule is test", json_schema_extra={"examples": [False]})
    description: Optional[StrictStr] = Field(default=None, description="description of the rule", json_schema_extra={"examples": ["secure customer example@example.com"]})
    __properties: ClassVar[List[str]] = ["id", "field", "created_at", "value", "is_global", "is_test", "description"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RiskRulesData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RiskRulesData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "field": obj.get("field"),
            "created_at": obj.get("created_at"),
            "value": obj.get("value"),
            "is_global": obj.get("is_global"),
            "is_test": obj.get("is_test"),
            "description": obj.get("description")
        })
        return _obj


