# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.3.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from conekta.models.subscription_details_card import SubscriptionDetailsCard
from conekta.models.subscription_details_plan import SubscriptionDetailsPlan
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SubscriptionDetails(BaseModel):
    """
    Subscription details for customer portal
    """ # noqa: E501
    card: Optional[SubscriptionDetailsCard] = None
    plan: Optional[SubscriptionDetailsPlan] = None
    id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["sub_2yYsQuYtXAbP1fdYu"]})
    object: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["subscription"]})
    status: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["canceled"]})
    plan_id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["VG5"]})
    customer_id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["cus_2yDzKtEAD3khH8Sga"]})
    next_billing_cycle: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1876833632]})
    created_at: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1755873642]})
    updated_at: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1761745218]})
    __properties: ClassVar[List[str]] = ["card", "plan", "id", "object", "status", "plan_id", "customer_id", "next_billing_cycle", "created_at", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubscriptionDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of card
        if self.card:
            _dict['card'] = self.card.to_dict()
        # override the default output from pydantic by calling `to_dict()` of plan
        if self.plan:
            _dict['plan'] = self.plan.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubscriptionDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "card": SubscriptionDetailsCard.from_dict(obj["card"]) if obj.get("card") is not None else None,
            "plan": SubscriptionDetailsPlan.from_dict(obj["plan"]) if obj.get("plan") is not None else None,
            "id": obj.get("id"),
            "object": obj.get("object"),
            "status": obj.get("status"),
            "plan_id": obj.get("plan_id"),
            "customer_id": obj.get("customer_id"),
            "next_billing_cycle": obj.get("next_billing_cycle"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


