# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.2.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SubscriptionDetailsCard(BaseModel):
    """
    SubscriptionDetailsCard
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["src_2yw5zPrVahTy7xy7P"]})
    created_at: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1761745218]})
    active: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [True]})
    object: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["card"]})
    exp_month: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["05"]})
    exp_year: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["26"]})
    brand: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["mastercard"]})
    last4: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["1005"]})
    name: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["test"]})
    payment_source_status: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["active"]})
    customer_id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["cus_2yDzKtEAD3khH8Sga"]})
    customer_custom_reference: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "created_at", "active", "object", "exp_month", "exp_year", "brand", "last4", "name", "payment_source_status", "customer_id", "customer_custom_reference"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubscriptionDetailsCard from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubscriptionDetailsCard from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created_at": obj.get("created_at"),
            "active": obj.get("active"),
            "object": obj.get("object"),
            "exp_month": obj.get("exp_month"),
            "exp_year": obj.get("exp_year"),
            "brand": obj.get("brand"),
            "last4": obj.get("last4"),
            "name": obj.get("name"),
            "payment_source_status": obj.get("payment_source_status"),
            "customer_id": obj.get("customer_id"),
            "customer_custom_reference": obj.get("customer_custom_reference")
        })
        return _obj


