# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.3.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SubscriptionDetailsPlan(BaseModel):
    """
    SubscriptionDetailsPlan
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["VG5"]})
    object: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["plan"]})
    name: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["CLARO"]})
    amount: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [30000]})
    currency: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["USD"]})
    interval: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["month"]})
    frequency: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1]})
    trial_period_days: Optional[StrictInt] = None
    expiry_count: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1]})
    created_at: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1742087277]})
    __properties: ClassVar[List[str]] = ["id", "object", "name", "amount", "currency", "interval", "frequency", "trial_period_days", "expiry_count", "created_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubscriptionDetailsPlan from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubscriptionDetailsPlan from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "object": obj.get("object"),
            "name": obj.get("name"),
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "interval": obj.get("interval"),
            "frequency": obj.get("frequency"),
            "trial_period_days": obj.get("trial_period_days"),
            "expiry_count": obj.get("expiry_count"),
            "created_at": obj.get("created_at")
        })
        return _obj


