# coding: utf-8

"""
    Conekta API

    Conekta sdk

    The version of the OpenAPI document: 2.2.0
    Contact: engineering@conekta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TokenRequestCard(BaseModel):
    """
    TokenRequestCard
    """ # noqa: E501
    cvc: Annotated[str, Field(strict=True, max_length=4)] = Field(description="It is a value that allows identifying the security code of the card.", json_schema_extra={"examples": ["123"]})
    device_fingerprint: Optional[StrictStr] = Field(default=None, description="It is a value that allows identifying the device fingerprint.", json_schema_extra={"examples": ["zptcxk4p6w1ijwz85snf1l3bqe5g09ie"]})
    exp_month: Annotated[str, Field(strict=True, max_length=2)] = Field(description="It is a value that allows identifying the expiration month of the card.", json_schema_extra={"examples": ["12"]})
    exp_year: Annotated[str, Field(strict=True, max_length=2)] = Field(description="It is a value that allows identifying the expiration year of the card.", json_schema_extra={"examples": ["26"]})
    name: StrictStr = Field(description="It is a value that allows identifying the name of the cardholder.", json_schema_extra={"examples": ["Miguel"]})
    number: StrictStr = Field(description="It is a value that allows identifying the number of the card.", json_schema_extra={"examples": ["4242424242424242"]})
    __properties: ClassVar[List[str]] = ["cvc", "device_fingerprint", "exp_month", "exp_year", "name", "number"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TokenRequestCard from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TokenRequestCard from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cvc": obj.get("cvc"),
            "device_fingerprint": obj.get("device_fingerprint"),
            "exp_month": obj.get("exp_month"),
            "exp_year": obj.get("exp_year"),
            "name": obj.get("name"),
            "number": obj.get("number")
        })
        return _obj


